var dash = document.querySelector("#dash");
var instructions = document.querySelector("#instructions");
var questions = document.  querySelector("#quiz")
// var quiz = document.querySelector("quiz")

// Show the section
// Show the section
document.getElementById('quiz').style.display = 'none';

// Hide the section


// Hide the section
// document.getElementById('sectionId').classList.remove('show');


// front page

// Instructions

start.addEventListener("click" , ()=>{
    instructions.style.display = "none"; 
    document.getElementById('quiz').style.display = 'block';
    

});


